(function() {var implementors = {};
implementors['typenum'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='enum' href='typenum/bit/enum.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='enum' href='typenum/bit/enum.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='enum' href='typenum/bit/enum.B0.html' title='typenum::bit::B0'>B0</a>&gt; for <a class='enum' href='typenum/bit/enum.B1.html' title='typenum::bit::B1'>B1</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='enum' href='typenum/bit/enum.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='enum' href='typenum/bit/enum.B0.html' title='typenum::bit::B0'>B0</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;<a class='enum' href='typenum/bit/enum.B1.html' title='typenum::bit::B1'>B1</a>&gt; for <a class='enum' href='typenum/bit/enum.B1.html' title='typenum::bit::B1'>B1</a>","impl&lt;Ur: <a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='enum' href='typenum/uint/enum.UTerm.html' title='typenum::uint::UTerm'>UTerm</a>","impl&lt;Ul: <a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>, Bl: <a class='trait' href='typenum/marker_traits/trait.Bit.html' title='typenum::marker_traits::Bit'>Bit</a>, Ur: <a class='trait' href='typenum/marker_traits/trait.Unsigned.html' title='typenum::marker_traits::Unsigned'>Unsigned</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.BitXor.html' title='core::ops::BitXor'>BitXor</a>&lt;Ur&gt; for <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt; <span class='where'>where <a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt;: PrivateXor&lt;Ur&gt;, PrivateXorOut&lt;<a class='struct' href='typenum/uint/struct.UInt.html' title='typenum::uint::UInt'>UInt</a>&lt;Ul, Bl&gt;, Ur&gt;: Trim</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
